"use client";
import { Decoration } from "@/components/decoration";
import "./globals.css";
import {
  ApolloClient,
  ApolloProvider,
  createHttpLink,
  InMemoryCache,
} from "@apollo/client";
import { setContext } from "@apollo/client/link/context";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Cookies from "js-cookie";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Authentication App",
  description: "Generated by create next app",
};

const httpLink = createHttpLink({
  uri: "https://opitdev.foraware.forcit.cloud",
});

const authLink = setContext((_, { headers }) => {
  const token = Cookies.get("token");

  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : "",
    },
  };
});

const client = new ApolloClient({
  link: authLink.concat(httpLink),
  cache: new InMemoryCache(),
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ApolloProvider client={client}>
        <body className={inter.className}>
          <div className="bg-white relative">
            <div
              className="flex flex-col items-center justify-between pt-0 lg:pr-10 pb-0 lg:pl-10 mt-0 mr-auto mb-0 ml-auto max-w-7xl
        xl:px-5 lg:flex-row"
            >
              <div className="flex flex-col justify-center h-screen items-center w-full px-0 md:px-10 lg:py-20 py-0 lg:flex-row">
                <div className="w-full h-full md:h-auto mr-0 mb-0 ml-0 relative z-10  mt-0 md:w-1/2">
                  <div
                    className="flex flex-col h-full items-start justify-start pt-10 pr-10 pb-10 pl-10 bg-white shadow-2xl rounded-xl
              relative z-10"
                  >
                    {children}
                  </div>
                  <Decoration />
                </div>
              </div>
            </div>
          </div>
        </body>
      </ApolloProvider>
    </html>
  );
}
